#!/usr/bin/env python
import json
import logging
import os
import sys

from evoeng.packages_extract import PackagesFile

logger = logging.getLogger(__name__)


def main() -> None:
	bin_path = sys.argv[1]

	with open(bin_path, "rb") as bin_file:
		print(f"Parsing {bin_path}")
		packages = PackagesFile(bin_file)

	warframes = extract_for_filter(packages, "Warframe")
	mods = extract_for_filter(packages, "Mod")
	weapons = extract_for_filter(packages, "Weapon")

	data = {"warframes": warframes, "mods": mods, "weapons": weapons}
	with open(f"data.json", "w") as f:
		json.dump(data, f)


def extract_for_filter(packages, tag_filter: str) -> list:
	print(f"Extracting: {tag_filter!r}")
	manifest = packages["/Lotus/Types/Lore/PrimaryCodexManifest"]
	ret = []
	entries = manifest.get("Entries", []) + manifest.get("AutoGeneratedEntries", [])
	for entry in entries:
		if entry.get("tag", "") == tag_filter:
			key = entry["type"]
			package = packages[key]
			ret.append({"path": key, "data": package})

	return ret


if __name__ == "__main__":
	main()
